# Generated by Django 4.2.7 on 2026-06-16 18:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Campaign Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('target_tier', models.CharField(choices=[('all', 'All'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='all', max_length=10, verbose_name='Target Tier')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Discount (%)')),
                ('voucher_code', models.CharField(max_length=50, verbose_name='Voucher Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaign',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=30, unique=True, verbose_name='Customer ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-binary', 'Non-binary'), ('Bigender', 'Bigender'), ('Genderfluid', 'Genderfluid'), ('Polygender', 'Polygender'), ('Agender', 'Agender'), ('Genderqueer', 'Genderqueer')], max_length=15, verbose_name='Gender')),
                ('income_level', models.CharField(choices=[('Low', 'Low'), ('Middle', 'Middle'), ('High', 'High')], max_length=10, verbose_name='Income Level')),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=15, verbose_name='Marital Status')),
                ('education_level', models.CharField(choices=[('High School', 'High School'), ("Bachelor's", "Bachelor's"), ("Master's", "Master's"), ('PhD', 'PhD'), ('Other', 'Other')], max_length=20, verbose_name='Education Level')),
                ('occupation', models.CharField(choices=[('Low', 'Low'), ('Middle', 'Middle'), ('High', 'High')], max_length=10, verbose_name='Occupation Level')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('purchase_channel', models.CharField(choices=[('Online', 'Online'), ('In-Store', 'In-Store'), ('Mixed', 'Mixed')], max_length=30, verbose_name='Purchase Channel')),
                ('social_media_influence', models.CharField(choices=[('None', 'None'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20, verbose_name='Social Media Influence')),
                ('discount_sensitivity', models.CharField(choices=[('Not Sensitive', 'Not Sensitive'), ('Somewhat Sensitive', 'Somewhat Sensitive'), ('Highly Sensitive', 'Highly Sensitive')], max_length=30, verbose_name='Discount Sensitivity')),
                ('device_used', models.CharField(max_length=30, verbose_name='Device Used')),
                ('payment_method', models.CharField(choices=[('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('PayPal', 'PayPal'), ('Cash', 'Cash'), ('Other', 'Other')], max_length=30, verbose_name='Payment Method')),
                ('shipping_preference', models.CharField(choices=[('Standard', 'Standard'), ('Express', 'Express'), ('No Preference', 'No Preference')], max_length=30, verbose_name='Shipping Preference')),
                ('purchase_intent', models.CharField(choices=[('Need-based', 'Need-based'), ('Wants-based', 'Wants-based'), ('Impulsive', 'Impulsive')], max_length=20, verbose_name='Purchase Intent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Transaction')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Transaction Date')),
                ('payment_method', models.CharField(choices=[('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('PayPal', 'PayPal'), ('Cash', 'Cash'), ('Other', 'Other')], max_length=30, verbose_name='Payment Method')),
                ('purchase_category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Purchase Category')),
                ('discount_used', models.BooleanField(default=False, verbose_name='Use Discount?')),
                ('frequency', models.IntegerField(default=1, verbose_name='Purchase Frequency')),
                ('satisfaction', models.IntegerField(default=5, verbose_name='Customer Satisfaction')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.customer')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('churn_probability', models.FloatField(default=0.0, verbose_name='Churn Probability (%)')),
                ('repurchase_probability', models.FloatField(default=0.0, verbose_name='Repurchase Probability (%)')),
                ('will_repurchase', models.BooleanField(default=True, verbose_name='Will Repurchase?')),
                ('predicted_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='core.customer')),
            ],
            options={
                'verbose_name': 'Prediction',
                'verbose_name_plural': 'Predictions',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, verbose_name='Total Points')),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', max_length=10, verbose_name='Level')),
                ('total_spending', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Spending')),
                ('is_member', models.BooleanField(default=False, verbose_name='Loyalty Member?')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty', to='core.customer')),
            ],
            options={
                'verbose_name': 'Loyalty',
                'verbose_name_plural': 'Loyalty',
            },
        ),
    ]
