# Generated by Django 4.2.7 on 2026-06-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='return_rate',
            field=models.IntegerField(default=0, verbose_name='Return Rate'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='time_to_decision',
            field=models.IntegerField(default=1, verbose_name='Decision Time (days)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='purchase_category',
            field=models.CharField(choices=[('Activewear', 'Activewear'), ('Baju Cosplay', 'Baju Cosplay'), ('Blouse', 'Blouse'), ('Bundled Set', 'Bundled Set'), ('Cardigan & Sweater', 'Cardigan & Sweater'), ('Casual Wear', 'Casual Wear'), ('Compression Wear', 'Compression Wear'), ('Dress', 'Dress'), ('Formal Wear', 'Formal Wear'), ('Graphic Tee', 'Graphic Tee'), ('Hoodie', 'Hoodie'), ('Jacket', 'Jacket'), ('Kids & Baby Wear', 'Kids & Baby Wear'), ('Loungewear', 'Loungewear'), ('Outdoor & Hiking Wear', 'Outdoor & Hiking Wear'), ('Pajamas & Sleepwear', 'Pajamas & Sleepwear'), ('Polo Shirt', 'Polo Shirt'), ('Resort Wear', 'Resort Wear'), ('Scrubs & Medical Wear', 'Scrubs & Medical Wear'), ('Skirt', 'Skirt'), ('Smart Wearables', 'Smart Wearables'), ('Sportswear', 'Sportswear'), ('T-Shirt', 'T-Shirt'), ('Travel Wear', 'Travel Wear'), ('Workwear & Blazer', 'Workwear & Blazer')], default=1, max_length=50, verbose_name='Purchase Category'),
            preserve_default=False,
        ),
    ]
