# Generated by Django 4.2.7 on 2026-06-15 20:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_campaign_id_alter_campaign_target_tier_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['id'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='predictionresult',
            options={'verbose_name': 'Prediction', 'verbose_name_plural': 'Predictions'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date'], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Discount (%)'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active?'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Campaign Name'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='target_tier',
            field=models.CharField(choices=[('all', 'All'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='all', max_length=10, verbose_name='Target Tier'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='voucher_code',
            field=models.CharField(max_length=50, verbose_name='Voucher Code'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.IntegerField(verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='device_used',
            field=models.CharField(max_length=30, verbose_name='Device Used'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='discount_sensitivity',
            field=models.CharField(choices=[('Not Sensitive', 'Not Sensitive'), ('Somewhat Sensitive', 'Somewhat Sensitive'), ('Highly Sensitive', 'Highly Sensitive')], max_length=30, verbose_name='Discount Sensitivity'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='payment_method',
            field=models.CharField(choices=[('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('PayPal', 'PayPal'), ('Cash', 'Cash'), ('Other', 'Other')], max_length=30, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='purchase_category',
            field=models.CharField(max_length=100, verbose_name='Purchase Category'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='purchase_channel',
            field=models.CharField(choices=[('Online', 'Online'), ('In-Store', 'In-Store'), ('Mixed', 'Mixed')], max_length=30, verbose_name='Purchase Channel'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='purchase_intent',
            field=models.CharField(choices=[('Need-based', 'Need-based'), ('Wants-based', 'Wants-based'), ('Impulsive', 'Impulsive')], max_length=20, verbose_name='Purchase Intent'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='shipping_preference',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Express', 'Express'), ('No Preference', 'No Preference')], max_length=30, verbose_name='Shipping Preference'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='social_media_influence',
            field=models.CharField(choices=[('None', 'None'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20, verbose_name='Social Media Influence'),
        ),
        migrations.AlterField(
            model_name='loyaltyprofile',
            name='is_member',
            field=models.BooleanField(default=False, verbose_name='Loyalty Member?'),
        ),
        migrations.AlterField(
            model_name='loyaltyprofile',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Total Points'),
        ),
        migrations.AlterField(
            model_name='loyaltyprofile',
            name='total_spending',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total Spending'),
        ),
        migrations.AlterField(
            model_name='predictionresult',
            name='churn_probability',
            field=models.FloatField(default=0.0, verbose_name='Churn Probability (%)'),
        ),
        migrations.AlterField(
            model_name='predictionresult',
            name='repurchase_probability',
            field=models.FloatField(default=0.0, verbose_name='Repurchase Probability (%)'),
        ),
        migrations.AlterField(
            model_name='predictionresult',
            name='will_repurchase',
            field=models.BooleanField(default=True, verbose_name='Will Repurchase?'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Transaction Date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='discount_used',
            field=models.BooleanField(default=False, verbose_name='Use Discount?'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='frequency',
            field=models.IntegerField(default=1, verbose_name='Purchase Frequency'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('PayPal', 'PayPal'), ('Cash', 'Cash'), ('Other', 'Other')], max_length=30, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='satisfaction',
            field=models.IntegerField(default=5, verbose_name='Customer Satisfaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time_to_decision',
            field=models.IntegerField(default=1, verbose_name='Decision Time (days)'),
        ),
    ]
