# Generated by Django 4.2.7 on 2026-06-16 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transaction_return_rate_transaction_time_to_decision_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='return_rate',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='time_to_decision',
        ),
    ]
