# Generated by Django 4.2.7 on 2026-06-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customer_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-binary', 'Non-binary'), ('Bigender', 'Bigender'), ('Genderfluid', 'Genderfluid'), ('Polygender', 'Polygender'), ('Agender', 'Agender'), ('Genderqueer', 'Genderqueer')], max_length=15, verbose_name='Gender'),
        ),
    ]
